const STORAGE_KEY = 'ion_community_app_data_v3';
const USER_KEY = 'mock_user';

const now = () => new Date().toISOString();

const defaultUser = {
  id: 'user_resident_001',
  email: 'resident@example.com',
  full_name: 'Budi Santoso',
  role: 'user',
  unit: 'Tower A - Unit 15',
  mock: true,
};

const seedData = {
  User: [
    defaultUser,
    {
      id: 'user_admin_001',
      email: 'admin@example.com',
      full_name: 'Rizky Pratama',
      role: 'admin',
      unit: 'Management Office',
      mock: true,
      created_date: '2026-01-01T00:00:00.000Z',
    },
    {
      id: 'user_resident_002',
      email: 'sari@example.com',
      full_name: 'Sari Dewi Anggraini',
      role: 'user',
      unit: 'Tower C - Unit 07',
      mock: true,
      created_date: '2026-01-10T08:00:00.000Z',
    },
    {
      id: 'user_resident_003',
      email: 'andi@example.com',
      full_name: 'Andi Kurniawan',
      role: 'user',
      unit: 'Tower D - Unit 12',
      mock: true,
      created_date: '2026-01-15T08:00:00.000Z',
    },
  ],

  Unit: [
    {
      id: 'unit_001',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      property_name: 'Damai Putra Residence',
      unit_number: 'A-1508',
      tower: 'A',
      floor: 15,
      floor_number: 15,
      cluster_name: 'Damai Putra',
      block_number: 'A',
      status: 'approved',
      ownership_status: 'owner',
      unit_type: 'Apartment',
      area_sqm: 72,
      area_size: 72,
      bedrooms: 2,
      bedroom_count: 2,
      bathrooms: 2,
      bathroom_count: 2,
      garage_count: 1,
      deposit_required: 15000000,
      owner_name: 'Budi Santoso',
      owner_phone: '0812-3456-7890',
      owner_email: 'resident@example.com',
      document_url: 'https://example.com/docs/sertifikat_A1508.pdf',
      created_date: '2026-01-05T08:00:00.000Z',
    },
    {
      id: 'unit_002',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      property_name: 'Sayana Apartments',
      unit_number: 'B-0902',
      tower: 'B',
      floor: 9,
      floor_number: 9,
      cluster_name: 'Sayana',
      block_number: 'B',
      status: 'approved',
      ownership_status: 'tenant',
      unit_type: 'Apartment',
      area_sqm: 45,
      area_size: 45,
      bedrooms: 1,
      bedroom_count: 1,
      bathrooms: 1,
      bathroom_count: 1,
      garage_count: 1,
      rent_start_date: '2026-01-01',
      rent_end_date: '2026-12-31',
      monthly_rent: 6500000,
      rent_payment_status: 'paid',
      deposit_required: 13000000,
      owner_name: 'Hendra Gunawan',
      owner_phone: '0878-9988-7766',
      owner_email: 'hendra.gunawan@example.com',
      document_url: 'https://example.com/docs/perjanjian_sewa_B0902.pdf',
      created_date: '2026-02-10T08:00:00.000Z',
    },
    {
      id: 'unit_003',
      user_email: 'sari@example.com',
      user_name: 'Sari Dewi Anggraini',
      property_name: 'Green Valley Residence',
      unit_number: 'C-0712',
      tower: 'C',
      floor: 7,
      floor_number: 7,
      cluster_name: 'Green Valley',
      block_number: 'C',
      status: 'approved',
      ownership_status: 'owner',
      unit_type: 'Apartment',
      area_sqm: 60,
      area_size: 60,
      bedrooms: 2,
      bedroom_count: 2,
      bathrooms: 1,
      bathroom_count: 1,
      garage_count: 1,
      deposit_required: 12000000,
      owner_name: 'Sari Dewi Anggraini',
      owner_phone: '0813-9876-5432',
      owner_email: 'sari@example.com',
      document_url: 'https://example.com/docs/sertifikat_C0712.pdf',
      created_date: '2026-01-20T08:00:00.000Z',
    },
    {
      id: 'unit_004',
      user_email: 'andi@example.com',
      user_name: 'Andi Kurniawan',
      property_name: 'Damai Putra Residence',
      unit_number: 'D-0305',
      tower: 'D',
      floor: 3,
      floor_number: 3,
      cluster_name: 'Damai Putra',
      block_number: 'D',
      status: 'pending',
      ownership_status: 'owner',
      unit_type: 'Studio',
      area_sqm: 32,
      area_size: 32,
      bedrooms: 1,
      bedroom_count: 1,
      bathrooms: 1,
      bathroom_count: 1,
      garage_count: 0,
      deposit_required: 8000000,
      owner_name: 'Andi Kurniawan',
      owner_phone: '0878-1122-3344',
      owner_email: 'andi@example.com',
      document_url: 'https://example.com/docs/sertifikat_D0305.pdf',
      created_date: '2026-03-01T08:00:00.000Z',
    },
  ],

  Property: [
    {
      id: 'property_001',
      name: 'Damai Putra Residence',
      title: 'Damai Putra Residence',
      category: 'apartment',
      location: 'Bekasi Utara, Jawa Barat',
      address: 'Jl. Perjuangan No. 88, Harapan Baru, Bekasi Utara, Jawa Barat 17124',
      description: 'Hunian modern dengan fasilitas lengkap dan lingkungan yang nyaman untuk keluarga. Dilengkapi dengan kolam renang olimpik, taman bermain anak, gym, dan pusat perbelanjaan dalam satu kawasan terpadu. Didesain dengan konsep smart living yang memadukan kenyamanan hunian dengan kemudahan akses ke berbagai fasilitas komunitas.',
      image_url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&q=80',
      gallery_urls: [
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=900&q=80',
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80',
        'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?w=900&q=80',
      ],
      promo_badge: 'Ready Stock',
      tower_info: '4 Tower (A, B, C, D) — 20 Lantai',
      lift_count: 8,
      facility_count: 24,
      land_size_min: 28,
      land_size_max: 72,
      bedroom_min: 1,
      bedroom_max: 3,
      bathroom_min: 1,
      bathroom_max: 2,
      parking_min: 1,
      parking_max: 2,
      price_start: 875000000,
      price: 'Mulai Rp 875 Juta',
      whatsapp_number: '628119876543',
      facilities: [
        'Kolam Renang Olimpik',
        'Gym & Fitness Center',
        'Area Bermain Anak',
        'Jogging Track',
        'Security 24 Jam',
        'CCTV Seluruh Area',
        'Masjid',
        'Klinik Kesehatan',
        'Minimarket',
        'Laundry',
        'Co-Working Space',
        'Parkir Basement',
      ],
      developer: 'PT Damai Putra Properti',
      year_built: 2022,
      total_units: 480,
      floors: 20,
      created_date: '2026-01-04T08:00:00.000Z',
    },
    {
      id: 'property_002',
      name: 'Sayana Apartments',
      title: 'Sayana Apartments',
      category: 'apartment',
      location: 'Kota Harapan Indah, Bekasi',
      address: 'Jl. Harapan Indah Boulevard Blok RC-4, Kota Harapan Indah, Bekasi 17131',
      description: 'Apartemen compact dengan desain modern yang berdekatan dengan pusat bisnis dan lifestyle. Ideal untuk profesional muda yang menginginkan kemudahan akses transportasi. Tersedia unit studio hingga 2 kamar dengan finishing premium dan pemandangan kota yang indah.',
      image_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=900&q=80',
      gallery_urls: [
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80',
        'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=80',
        'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80',
      ],
      promo_badge: 'Hot Deal',
      tower_info: '2 Tower (B1, B2) — 15 Lantai',
      lift_count: 4,
      facility_count: 16,
      land_size_min: 22,
      land_size_max: 45,
      bedroom_min: 1,
      bedroom_max: 2,
      bathroom_min: 1,
      bathroom_max: 2,
      parking_min: 1,
      parking_max: 1,
      price_start: 625000000,
      price: 'Mulai Rp 625 Juta',
      whatsapp_number: '628118765432',
      facilities: [
        'Rooftop Garden',
        'Co-Working Space',
        'Cafe & Lounge',
        'Parkir Basement',
        'Kolam Renang Rooftop',
        'Gym',
        'Security 24 Jam',
        'CCTV',
        'High-Speed Internet',
        'Bike Parking',
      ],
      developer: 'PT Sayana Property Group',
      year_built: 2023,
      total_units: 320,
      floors: 15,
      created_date: '2026-01-08T08:00:00.000Z',
    },
    {
      id: 'property_003',
      name: 'Green Valley Residence',
      title: 'Green Valley Residence',
      category: 'residential',
      location: 'Cikarang Barat, Bekasi',
      address: 'Jl. Taman Hijau Raya No. 12, Cikarang Barat, Kabupaten Bekasi 17530',
      description: 'Kawasan hunian asri dengan konsep green living. Dikelilingi taman dan area hijau seluas 2 hektar, memberikan kesejukan dan kenyamanan di tengah kota industri. Cocok untuk keluarga yang mengutamakan lingkungan hijau dan udara segar.',
      image_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80',
      gallery_urls: [
        'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&q=80',
        'https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=900&q=80',
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
      ],
      tower_info: '3 Tower (C1, C2, C3) — 12 Lantai',
      lift_count: 6,
      facility_count: 18,
      land_size_min: 36,
      land_size_max: 60,
      bedroom_min: 2,
      bedroom_max: 3,
      bathroom_min: 1,
      bathroom_max: 2,
      parking_min: 1,
      parking_max: 2,
      price_start: 530000000,
      price: 'Mulai Rp 530 Juta',
      whatsapp_number: '628117654321',
      facilities: [
        'Taman Hijau 2 Hektar',
        'Jogging Track',
        'Kolam Renang',
        'Playground Anak',
        'Mushola',
        'Minimarket',
        'Security 24 Jam',
        'CCTV',
        'Barbecue Area',
        'Dog Walking Area',
      ],
      developer: 'PT Green Valley Development',
      year_built: 2021,
      total_units: 240,
      floors: 12,
      created_date: '2026-01-10T08:00:00.000Z',
    },
    {
      id: 'property_004',
      name: 'ION Tower Premium',
      title: 'ION Tower Premium',
      category: 'apartment',
      location: 'Jababeka, Cikarang',
      address: 'Jl. Jababeka Raya No. 1, Kawasan Industri Jababeka, Cikarang Utara 17530',
      description: 'Menara hunian premium dengan view kota dan fasilitas eksklusif setara hotel bintang 5. Dilengkapi sky lounge, infinity pool di lantai 25, dan concierge service 24 jam. Cocok untuk investasi properti dengan potensi return tinggi di kawasan industri terbesar Jababeka.',
      image_url: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=900&q=80',
      gallery_urls: [
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80',
        'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=900&q=80',
        'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=900&q=80',
      ],
      promo_badge: 'Premium',
      tower_info: '1 Tower — 28 Lantai',
      lift_count: 6,
      facility_count: 20,
      land_size_min: 32,
      land_size_max: 96,
      bedroom_min: 1,
      bedroom_max: 3,
      bathroom_min: 1,
      bathroom_max: 3,
      parking_min: 1,
      parking_max: 2,
      price_start: 1150000000,
      price: 'Mulai Rp 1,15 Miliar',
      whatsapp_number: '628116543210',
      facilities: [
        'Sky Lounge (Lt. 27)',
        'Infinity Pool (Lt. 25)',
        'Concierge 24 Jam',
        'Business Center',
        'Fine Dining Restaurant',
        'Spa & Wellness',
        'Gym Premium',
        'Meeting Rooms',
        'Valet Parking',
        'EV Charging Station',
        'Smart Home System',
        'High-Speed Internet 1 Gbps',
      ],
      developer: 'PT ION Property Nusantara',
      year_built: 2024,
      total_units: 180,
      floors: 28,
      created_date: '2026-02-01T08:00:00.000Z',
    },
  ],

  Destination: [
    {
      id: 'destination_001',
      name: 'Central Park',
      title: 'Central Park',
      category: 'Lifestyle',
      image_url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=900&q=80',
      hero_image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=900&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1560178404-5059082c59ec?w=900&q=80',
        'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?w=900&q=80',
        'https://images.unsplash.com/photo-1530655638484-de9b8edc0b68?w=900&q=80',
      ],
      description: 'Ruang hijau outdoor seluas 1,5 hektar untuk bersantai, piknik keluarga, dan berbagai kegiatan komunitas. Dilengkapi panggung terbuka, area food truck setiap akhir pekan, dan jalur refleksi. Tempat favorit warga untuk olahraga pagi dan berkumpul bersama.',
      opening_hours: '06:00 - 22:00',
      location: 'Area B, Damai Putra Residence',
      website_url: '',
      created_date: '2026-01-12T08:00:00.000Z',
    },
    {
      id: 'destination_002',
      name: 'Food Avenue',
      title: 'Food Avenue',
      category: 'Culinary',
      image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80',
      hero_image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=80',
        'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=900&q=80',
        'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=900&q=80',
      ],
      description: 'Deretan restoran dan kafe pilihan dengan menu dari berbagai penjuru nusantara hingga mancanegara. Terdapat 10 tenant kuliner yang menawarkan pengalaman makan terbaik — dari sarapan pagi hingga makan malam romantis.',
      opening_hours: '07:00 - 22:00',
      location: 'Area C, Ground Floor, Damai Putra Residence',
      website_url: '',
      created_date: '2026-01-13T08:00:00.000Z',
    },
    {
      id: 'destination_003',
      name: 'Sport Complex',
      title: 'Sport Complex',
      category: 'Sport & Recreation',
      image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=900&q=80',
      hero_image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=900&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=900&q=80',
        'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=900&q=80',
        'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=900&q=80',
      ],
      description: 'Pusat olahraga terpadu dengan 2 lapangan futsal indoor, 4 lapangan badminton, 1 lapangan basket, kolam renang olimpik 25m, dan gym modern berkapasitas 200 orang. Booking lapangan bisa dilakukan melalui aplikasi ION.',
      opening_hours: '05:00 - 23:00',
      location: 'Area D, Damai Putra Residence',
      website_url: '',
      created_date: '2026-01-14T08:00:00.000Z',
    },
    {
      id: 'destination_004',
      name: 'ION Mall',
      title: 'ION Mall',
      category: 'Shopping',
      image_url: 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=900&q=80',
      hero_image: 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=900&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=900&q=80',
        'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=900&q=80',
        'https://images.unsplash.com/photo-1481437156560-3205f6a55735?w=900&q=80',
      ],
      description: 'Pusat perbelanjaan modern 3 lantai dengan lebih dari 50 tenant pilihan. Tersedia fashion, elektronik, supermarket 24 jam, bioskop 4 layar, food court, dan zona hiburan keluarga. Akses langsung dari lobby Tower A.',
      opening_hours: '10:00 - 22:00',
      location: 'Area A, Main Building, Damai Putra Residence',
      website_url: '',
      created_date: '2026-01-15T08:00:00.000Z',
    },
    {
      id: 'destination_005',
      name: 'Wellness Center',
      title: 'Wellness Center',
      category: 'Health & Beauty',
      image_url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&q=80',
      hero_image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&q=80',
      gallery: [
        'https://images.unsplash.com/photo-1552693673-1bf958298935?w=900&q=80',
        'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=900&q=80',
        'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=900&q=80',
      ],
      description: 'Pusat kesehatan dan kecantikan terpadu dengan layanan spa premium, salon lengkap, klinik kesehatan umum & gigi, laboratorium, dan apotek 24 jam. Konsultasi dokter online tersedia melalui aplikasi ION.',
      opening_hours: '08:00 - 21:00',
      location: 'Area E, Level 2, Damai Putra Residence',
      website_url: '',
      created_date: '2026-01-20T08:00:00.000Z',
    },
  ],

  Tenant: [
    {
      id: 'tenant_001',
      destination_id: 'destination_002',
      destination_name: 'Food Avenue',
      name: 'Kopi Network',
      category: 'Cafe',
      image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=900&q=80',
      logo_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=200&q=80',
      description: 'Specialty coffee dari biji pilihan Aceh dan Flores. Tersedia berbagai pilihan metode seduh manual brew (V60, Chemex, Aeropress), espresso based, dan minuman non-kafein untuk yang tidak suka kopi. Camilan pastry segar tersedia setiap hari.',
      rating: 4.8,
      price_range: 'Rp 25.000 - 65.000',
      opening_hours: '07:00 - 22:00',
      location_detail: 'Food Avenue, Unit A-01, Ground Floor',
      contact: '0811-2233-4455',
      created_date: '2026-01-15T08:00:00.000Z',
    },
    {
      id: 'tenant_002',
      destination_id: 'destination_002',
      destination_name: 'Food Avenue',
      name: 'Rasa Nusantara',
      category: 'Restaurant',
      image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=80',
      logo_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=200&q=80',
      description: 'Masakan Indonesia otentik dari berbagai daerah: rendang Padang, soto Betawi, nasi liwet Solo, gado-gado, sate madura, dan berbagai hidangan comfort food nusantara. Cocok untuk makan siang dan makan malam keluarga.',
      rating: 4.6,
      price_range: 'Rp 35.000 - 120.000',
      opening_hours: '10:00 - 21:00',
      location_detail: 'Food Avenue, Unit B-02, Ground Floor',
      contact: '0812-3344-5566',
      created_date: '2026-01-16T08:00:00.000Z',
    },
    {
      id: 'tenant_003',
      destination_id: 'destination_002',
      destination_name: 'Food Avenue',
      name: 'Burger Republic',
      category: 'Fast Food',
      image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=900&q=80',
      logo_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=200&q=80',
      description: 'Burger premium dengan patty wagyu 100% lokal. Menu unggulan: Double Wagyu Smash, Crispy Chicken Avocado, dan Beyond Burger untuk vegan. Tersedia paket hemat untuk keluarga dan delivery via GoFood & GrabFood.',
      rating: 4.4,
      price_range: 'Rp 45.000 - 95.000',
      opening_hours: '11:00 - 22:00',
      location_detail: 'Food Avenue, Unit C-03, Ground Floor',
      contact: '0813-4455-6677',
      created_date: '2026-01-17T08:00:00.000Z',
    },
    {
      id: 'tenant_004',
      destination_id: 'destination_002',
      destination_name: 'Food Avenue',
      name: 'Mie Galaksi',
      category: 'Restaurant',
      image_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=900&q=80',
      logo_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=200&q=80',
      description: 'Mie ayam dan bakso artisan dengan kaldu sapi asli yang dimasak 12 jam. Menu andalan: Mie Yamin Special, Bakso Mercon isi daging sapi, dan Baso Bakar khas Bandung. Tersedia pilihan kuah atau kering.',
      rating: 4.7,
      price_range: 'Rp 20.000 - 55.000',
      opening_hours: '09:00 - 21:00',
      location_detail: 'Food Avenue, Unit D-04, Ground Floor',
      contact: '0814-5566-7788',
      created_date: '2026-01-18T08:00:00.000Z',
    },
    {
      id: 'tenant_005',
      destination_id: 'destination_002',
      destination_name: 'Food Avenue',
      name: 'Juice & Bowl Corner',
      category: 'Beverages',
      image_url: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=900&q=80',
      logo_url: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=200&q=80',
      description: 'Jus buah segar cold-pressed, smoothie bowl, acai bowl, dan minuman kesehatan untuk gaya hidup aktif. Semua dibuat dari buah-buahan segar pilihan tanpa tambahan gula, pengawet, dan pewarna buatan.',
      rating: 4.5,
      price_range: 'Rp 30.000 - 75.000',
      opening_hours: '07:00 - 20:00',
      location_detail: 'Food Avenue, Unit E-05, Ground Floor',
      contact: '0815-6677-8899',
      created_date: '2026-01-19T08:00:00.000Z',
    },
    {
      id: 'tenant_006',
      destination_id: 'destination_002',
      destination_name: 'Food Avenue',
      name: 'Artisan Bakery',
      category: 'Bakery',
      image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=900&q=80',
      logo_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=200&q=80',
      description: 'Roti artisan dan kue premium yang dipanggang segar setiap pagi mulai pukul 05:00. Pilihan: croissant butter, sourdough, danish fruit, pain au chocolat, cheese cake, dan berbagai pastry premium impor Prancis.',
      rating: 4.9,
      price_range: 'Rp 15.000 - 80.000',
      opening_hours: '06:30 - 20:00',
      location_detail: 'Food Avenue, Unit F-06, Ground Floor',
      contact: '0816-7788-9900',
      created_date: '2026-01-20T08:00:00.000Z',
    },
    {
      id: 'tenant_007',
      destination_id: 'destination_003',
      destination_name: 'Sport Complex',
      name: 'Iron Fitness Gym',
      category: 'Gym & Fitness',
      image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=900&q=80',
      logo_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200&q=80',
      description: 'Gym modern 800m² dengan peralatan strength training dan cardio kelas dunia dari Life Fitness & Technogym. Tersedia 5 personal trainer bersertifikat internasional (ACE/NASM), kelas group fitness (HIIT, yoga, pilates, zumba), dan sauna.',
      rating: 4.6,
      price_range: 'Rp 150.000 - 400.000 / bulan',
      opening_hours: '05:00 - 23:00',
      location_detail: 'Sport Complex, Lantai 1, Area D',
      contact: '0817-8899-0011',
      created_date: '2026-01-21T08:00:00.000Z',
    },
    {
      id: 'tenant_008',
      destination_id: 'destination_004',
      destination_name: 'ION Mall',
      name: 'ION Supermarket',
      category: 'Supermarket',
      image_url: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=900&q=80',
      logo_url: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=200&q=80',
      description: 'Supermarket lengkap buka 24 jam dengan 5.000+ produk: sayur & buah segar harian, daging & seafood segar, produk impor pilihan, kebutuhan bayi, peralatan rumah tangga, dan personal care. Member card warga ION mendapat diskon 5% setiap hari.',
      rating: 4.3,
      price_range: 'Harga bersaing',
      opening_hours: '00:00 - 24:00',
      location_detail: 'ION Mall, Ground Floor, Area A',
      contact: '0818-9900-1122',
      created_date: '2026-01-22T08:00:00.000Z',
    },
    {
      id: 'tenant_009',
      destination_id: 'destination_005',
      destination_name: 'Wellness Center',
      name: 'Serene Spa & Salon',
      category: 'Spa & Beauty',
      image_url: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=900&q=80',
      logo_url: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=200&q=80',
      description: 'Spa dan salon premium dengan 12 treatment room. Layanan: Swedish & deep tissue massage, aromatherapy, hot stone, facial, body scrub, mani-pedi, haircut, color & styling, dan bridal package. Booking via aplikasi ION dapatkan diskon 10%.',
      rating: 4.8,
      price_range: 'Rp 100.000 - 800.000',
      opening_hours: '09:00 - 21:00',
      location_detail: 'Wellness Center, Level 2, Area E',
      contact: '0819-0011-2233',
      created_date: '2026-01-25T08:00:00.000Z',
    },
    {
      id: 'tenant_010',
      destination_id: 'destination_005',
      destination_name: 'Wellness Center',
      name: 'Klinik Sehat Bersama',
      category: 'Klinik Kesehatan',
      image_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=900&q=80',
      logo_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=200&q=80',
      description: 'Klinik kesehatan terpadu dengan 4 dokter umum, 2 dokter gigi, laboratorium klinik, dan apotek 24 jam. Layanan: konsultasi umum, vaksinasi, cek lab darah & urin, rontgen, dan homecare. Konsultasi online 24 jam via aplikasi ION.',
      rating: 4.5,
      price_range: 'Rp 50.000 - 250.000 / konsultasi',
      opening_hours: '08:00 - 22:00',
      location_detail: 'Wellness Center, Level 2, Area E',
      contact: '0821-1122-3344',
      created_date: '2026-01-26T08:00:00.000Z',
    },
  ],

  Event: [
    {
      id: 'event_001',
      title: 'Spring Garden Festival 2026',
      name: 'Spring Garden Festival 2026',
      start_date: '2026-06-01',
      end_date: '2026-06-15',
      start_time: '09:00',
      end_time: '21:00',
      location: 'Central Park, Area B',
      address: 'Central Park, Area B, Damai Putra Residence, Bekasi Utara',
      image_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=900&q=80',
      banner_image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=900&q=80',
      description: 'Festival musim semi tahunan dengan bazar komunitas, pertunjukan musik live, workshop berkebun, dan berbagai aktivitas keluarga selama 2 minggu penuh.',
      organizer: 'ION Community Management',
      category: 'Festival',
      is_free: true,
      is_featured: true,
      max_participants: 500,
      status: 'upcoming',
      ticket_url: '',
      created_date: '2026-02-01T08:00:00.000Z',
    },
    {
      id: 'event_002',
      title: 'Pemeriksaan Kesehatan Gratis Warga',
      name: 'Pemeriksaan Kesehatan Gratis Warga',
      start_date: '2026-05-20',
      end_date: '2026-05-20',
      start_time: '08:00',
      end_time: '16:00',
      location: 'Ballroom Utama, Lantai 1',
      address: 'Ballroom Utama, Lantai 1, Tower A, Damai Putra Residence',
      image_url: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=900&q=80',
      banner_image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=900&q=80',
      description: 'Program pemeriksaan kesehatan gratis meliputi cek tekanan darah, gula darah, kolesterol, dan konsultasi dengan dokter umum. Dibuka untuk semua warga dan keluarga.',
      organizer: 'Klinik Sehat Bersama & ION Management',
      category: 'Kesehatan',
      is_free: true,
      is_featured: false,
      max_participants: 200,
      status: 'upcoming',
      ticket_url: '',
      created_date: '2026-02-15T08:00:00.000Z',
    },
    {
      id: 'event_003',
      title: 'Gathering Warga Q2 2026',
      name: 'Gathering Warga Q2 2026',
      start_date: '2026-05-30',
      end_date: '2026-05-30',
      start_time: '16:00',
      end_time: '21:00',
      location: 'Central Park, Panggung Utama',
      address: 'Central Park, Panggung Utama, Area B, Damai Putra Residence',
      image_url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=900&q=80',
      banner_image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=900&q=80',
      description: 'Pertemuan akbar warga triwulan kedua. Agenda: laporan manajemen, diskusi fasilitas, pengumuman program baru, dan hiburan bersama. Dihadiri seluruh penghuni aktif.',
      organizer: 'ION Community Management',
      category: 'Komunitas',
      is_free: true,
      is_featured: true,
      max_participants: 800,
      status: 'upcoming',
      ticket_url: '',
      created_date: '2026-03-01T08:00:00.000Z',
    },
    {
      id: 'event_004',
      title: 'Lomba Mewarnai & Menggambar Anak',
      name: 'Lomba Mewarnai & Menggambar Anak',
      start_date: '2026-06-07',
      end_date: '2026-06-07',
      start_time: '09:00',
      end_time: '14:00',
      location: 'Playroom, Lantai 2',
      address: 'Playroom, Lantai 2, Tower A, Damai Putra Residence',
      image_url: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=900&q=80',
      banner_image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=900&q=80',
      description: 'Kompetisi seni untuk anak-anak usia 4-12 tahun. Kategori mewarnai (4-7 tahun) dan menggambar bebas (8-12 tahun). Hadiah menarik dan piagam penghargaan untuk semua peserta.',
      organizer: 'ION Kids Club',
      category: 'Anak & Keluarga',
      is_free: true,
      is_featured: false,
      max_participants: 100,
      status: 'upcoming',
      ticket_url: '',
      created_date: '2026-03-10T08:00:00.000Z',
    },
    {
      id: 'event_005',
      title: 'Yoga Pagi Bersama',
      name: 'Yoga Pagi Bersama',
      start_date: '2026-05-12',
      end_date: '2026-05-31',
      start_time: '06:30',
      end_time: '07:30',
      location: 'Central Park, Area Rumput',
      address: 'Central Park, Area Rumput Utama, Area B, Damai Putra Residence',
      image_url: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=900&q=80',
      banner_image: 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=900&q=80',
      description: 'Sesi yoga outdoor setiap Senin, Rabu, dan Jumat pagi pukul 06:30. Dipandu instruktur bersertifikat internasional. Bawa matras sendiri atau sewa di tempat.',
      organizer: 'ION Wellness Club',
      category: 'Olahraga & Kesehatan',
      is_free: false,
      is_featured: false,
      price: 25000,
      max_participants: 30,
      status: 'ongoing',
      ticket_url: '',
      created_date: '2026-03-15T08:00:00.000Z',
    },
    {
      id: 'event_006',
      title: 'Turnamen Badminton Antar Tower',
      name: 'Turnamen Badminton Antar Tower',
      start_date: '2026-06-14',
      end_date: '2026-06-22',
      start_time: '08:00',
      end_time: '20:00',
      location: 'Sport Complex, Lapangan Badminton',
      address: 'Sport Complex, Lapangan Badminton, Area D, Damai Putra Residence',
      image_url: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=900&q=80',
      banner_image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=900&q=80',
      description: 'Turnamen badminton bergengsi antar penghuni tower A, B, C, dan D. Kategori tunggal putra, tunggal putri, dan ganda campuran. Hadiah total senilai Rp 5 juta.',
      organizer: 'ION Sports Committee',
      category: 'Olahraga',
      is_free: false,
      is_featured: true,
      price: 50000,
      max_participants: 64,
      status: 'upcoming',
      ticket_url: '',
      created_date: '2026-04-01T08:00:00.000Z',
    },
  ],

  Ticket: [
    {
      id: 'ticket_001',
      ticket_number: 'TCK-2026-0001',
      unit_id: 'unit_001',
      user_email: 'resident@example.com',
      issue_type: 'Maintenance',
      title: 'AC unit kamar tidur tidak dingin',
      description: 'AC di kamar tidur utama (unit A-1508) tidak dingin sejak 3 hari lalu. Sudah dicoba reset tapi tidak berhasil. Mohon segera ditangani karena cuaca sedang panas.',
      status: 'Open',
      priority: 'High',
      created_date: '2026-05-01T08:00:00.000Z',
    },
    {
      id: 'ticket_002',
      ticket_number: 'TCK-2026-0002',
      unit_id: 'unit_001',
      user_email: 'resident@example.com',
      issue_type: 'Plumbing',
      title: 'Kebocoran pipa di bawah wastafel dapur',
      description: 'Ada rembesan air dari sambungan pipa di bawah wastafel dapur. Sudah dipasang ember tapi perlu perbaikan segera. Khawatir merusak lemari di bawahnya.',
      status: 'In Progress',
      priority: 'High',
      assigned_to: 'Tim Teknik - Pak Rudi',
      created_date: '2026-04-28T09:30:00.000Z',
    },
    {
      id: 'ticket_003',
      ticket_number: 'TCK-2026-0003',
      unit_id: 'unit_001',
      user_email: 'resident@example.com',
      issue_type: 'Electrical',
      title: 'Lampu koridor lantai 15 mati',
      description: 'Beberapa lampu di koridor lantai 15 dekat lift mati sejak seminggu lalu. Kondisi gelap dan kurang aman terutama malam hari.',
      status: 'Resolved',
      priority: 'Medium',
      assigned_to: 'Tim Elektrikal',
      resolution: 'Lampu sudah diganti dengan yang baru. Sudah dicek dan berfungsi normal.',
      resolved_at: '2026-04-25T14:00:00.000Z',
      created_date: '2026-04-20T10:00:00.000Z',
    },
    {
      id: 'ticket_004',
      ticket_number: 'TCK-2026-0004',
      unit_id: 'unit_001',
      user_email: 'resident@example.com',
      issue_type: 'Security',
      title: 'Kartu akses parkir tidak berfungsi',
      description: 'Kartu akses parkir saya (nomor kendaraan B 1234 XYZ) tidak terbaca di gate parkir sejak kemarin. Mohon dicek apakah ada masalah pada kartu atau reader.',
      status: 'Closed',
      priority: 'Low',
      resolution: 'Kartu akses sudah direset dan berfungsi kembali. Disarankan hindari meletakkan kartu berdekatan dengan benda bermagnet.',
      resolved_at: '2026-04-18T11:00:00.000Z',
      created_date: '2026-04-17T15:00:00.000Z',
    },
    {
      id: 'ticket_005',
      ticket_number: 'TCK-2026-0005',
      unit_id: 'unit_002',
      user_email: 'resident@example.com',
      issue_type: 'Internet',
      title: 'Koneksi internet sangat lambat',
      description: 'Internet di unit B-0902 sangat lambat sejak upgrade ke paket baru 5 hari yang lalu. Sudah test speed dan hasilnya hanya 2 Mbps padahal kontrak 50 Mbps.',
      status: 'Open',
      priority: 'Medium',
      created_date: '2026-05-05T16:00:00.000Z',
    },
    {
      id: 'ticket_006',
      ticket_number: 'TCK-2026-0006',
      unit_id: 'unit_001',
      user_email: 'resident@example.com',
      issue_type: 'Maintenance',
      title: 'Pintu kamar mandi susah ditutup',
      description: 'Engsel pintu kamar mandi sudah longgar sehingga pintu tidak bisa ditutup rapat. Mohon dikirim teknisi untuk perbaikan.',
      status: 'In Progress',
      priority: 'Low',
      assigned_to: 'Tim Sipil - Pak Dedi',
      created_date: '2026-05-08T11:00:00.000Z',
    },
  ],

  PermitApplication: [
    {
      id: 'permit_001',
      application_number: 'PRM-2026-0001',
      permit_number: 'PRM-2026-0001',
      unit_id: 'unit_001',
      unit_number: 'A-1508',
      user_email: 'resident@example.com',
      applicant_name: 'Budi Santoso',
      phone_number: '0812-3456-7890',
      email: 'resident@example.com',
      address: 'Tower A, Unit 1508, Damai Putra Residence, Bekasi Utara',
      property_type: 'Apartment',
      permit_type: 'Renovation',
      scope_of_work: 'Renovasi interior kamar tidur utama: pengecatan ulang, penggantian flooring vinyl, dan penambahan lemari built-in.',
      renovation_description: 'Renovasi interior kamar tidur utama meliputi pengecatan ulang seluruh dinding dengan cat premium, penggantian flooring lama dengan vinyl motif kayu, serta penambahan lemari built-in di sisi dinding sebelah kanan.',
      work_scope_summary: 'Pengecatan interior, penggantian flooring vinyl, pemasangan lemari built-in',
      contractor_name: 'CV Jaya Konstruksi',
      contractor_phone: '0812-3456-7890',
      estimated_duration_days: 14,
      duration_days: 14,
      num_workers: 4,
      start_date: '2026-05-15',
      end_date: '2026-05-28',
      submission_date: '2026-04-05',
      application_status: 'approved',
      current_approval_stage: 'completed',
      deposit_amount: 5000000,
      deposit_status: 'paid',
      notes_from_applicant: 'Mohon pekerjaan dilakukan dengan hati-hati karena ada furnitur mahal di sekitar area kerja.',
      approved_by: 'Rizky Pratama',
      approved_at: '2026-04-10T10:00:00.000Z',
      created_date: '2026-04-05T08:00:00.000Z',
    },
    {
      id: 'permit_002',
      application_number: 'PRM-2026-0002',
      permit_number: 'PRM-2026-0002',
      unit_id: 'unit_001',
      unit_number: 'A-1508',
      user_email: 'resident@example.com',
      applicant_name: 'Budi Santoso',
      phone_number: '0812-3456-7890',
      email: 'resident@example.com',
      address: 'Tower A, Unit 1508, Damai Putra Residence, Bekasi Utara',
      property_type: 'Apartment',
      permit_type: 'Electrical',
      scope_of_work: 'Penambahan stop kontak di ruang kerja dan penggantian MCB panel listrik yang sudah tua.',
      renovation_description: 'Pemasangan 4 stop kontak baru di area ruang kerja dan penggantian MCB lama dengan MCB baru berkapasitas lebih tinggi.',
      work_scope_summary: 'Penambahan stop kontak, penggantian MCB panel listrik',
      contractor_name: 'PT Listrik Mandiri',
      contractor_phone: '0813-2345-6789',
      estimated_duration_days: 3,
      duration_days: 3,
      num_workers: 2,
      start_date: '2026-05-20',
      end_date: '2026-05-22',
      submission_date: '2026-05-10',
      application_status: 'Submitted',
      current_approval_stage: 'document_check',
      deposit_amount: 2000000,
      deposit_status: 'paid',
      notes_from_applicant: 'Pekerjaan listrik perlu diselesaikan sebelum 25 Mei karena akan ada pemasangan perangkat baru.',
      created_date: '2026-05-10T08:00:00.000Z',
    },
    {
      id: 'permit_003',
      application_number: 'PRM-2026-0003',
      permit_number: 'PRM-2026-0003',
      unit_id: 'unit_002',
      unit_number: 'B-0902',
      user_email: 'resident@example.com',
      applicant_name: 'Budi Santoso',
      phone_number: '0812-3456-7890',
      email: 'resident@example.com',
      address: 'Tower B, Unit 0902, Sayana Apartments, Bekasi',
      property_type: 'Apartment',
      permit_type: 'Plumbing',
      scope_of_work: 'Perbaikan instalasi air bersih dan penggantian kloset lama dengan model baru.',
      renovation_description: 'Perbaikan kebocoran pada pipa utama air bersih kamar mandi dan penggantian unit kloset duduk lama dengan model baru yang lebih efisien.',
      work_scope_summary: 'Perbaikan pipa air bersih, penggantian kloset',
      contractor_name: 'UD Berkah Plumbing',
      contractor_phone: '0811-9876-5432',
      estimated_duration_days: 2,
      duration_days: 2,
      num_workers: 2,
      start_date: '2026-05-25',
      end_date: '2026-05-26',
      submission_date: '2026-05-08',
      application_status: 'inspection_required',
      current_approval_stage: 'building_infrastructure_review',
      deposit_amount: 1500000,
      deposit_status: 'paid',
      notes_from_applicant: 'Tolong diinspeksi dulu kondisi pipa lama sebelum pekerjaan dimulai.',
      created_date: '2026-05-08T09:00:00.000Z',
    },
    {
      id: 'permit_004',
      application_number: 'PRM-2026-0004',
      permit_number: 'PRM-2026-0004',
      unit_id: 'unit_001',
      unit_number: 'A-1508',
      user_email: 'resident@example.com',
      applicant_name: 'Budi Santoso',
      phone_number: '0812-3456-7890',
      email: 'resident@example.com',
      address: 'Tower A, Unit 1508, Damai Putra Residence, Bekasi Utara',
      property_type: 'Apartment',
      permit_type: 'Interior',
      scope_of_work: 'Penambahan partisi ruangan untuk membuat area kerja yang terpisah di ruang tamu.',
      renovation_description: 'Pemasangan partisi gypsum setinggi 2 meter untuk memisahkan area kerja dari ruang tamu utama.',
      work_scope_summary: 'Pemasangan partisi gypsum pembatas ruang kerja',
      contractor_name: 'Studio Interior Kreatif',
      contractor_phone: '0878-5432-1098',
      estimated_duration_days: 5,
      duration_days: 5,
      num_workers: 3,
      start_date: '2026-06-01',
      end_date: '2026-06-05',
      submission_date: '2026-05-01',
      application_status: 'rejected',
      current_approval_stage: 'head_approval',
      rejection_note: 'Partisi permanen tidak diperbolehkan sesuai peraturan bangunan pasal 7. Disarankan menggunakan partisi portable.',
      deposit_amount: 3000000,
      deposit_status: 'refunded',
      notes_from_applicant: 'Perlu ruang kerja yang lebih privat untuk kebutuhan WFH.',
      created_date: '2026-05-01T10:00:00.000Z',
    },
  ],

  WorkItem: [
    {
      id: 'work_item_master_001',
      work_item_name: 'Pengecatan Interior',
      work_category: 'Interior',
      work_item_type: 'General',
      description: 'Pengecatan dinding dan plafon dengan cat premium water-based',
      is_master: true,
      created_date: '2026-01-01T08:00:00.000Z',
    },
    {
      id: 'work_item_master_002',
      work_item_name: 'Instalasi Listrik',
      work_category: 'MEP',
      work_item_type: 'Electrical',
      description: 'Pemasangan atau modifikasi instalasi listrik termasuk kabel, stop kontak, dan saklar',
      is_master: true,
      created_date: '2026-01-01T08:05:00.000Z',
    },
    {
      id: 'work_item_master_003',
      work_item_name: 'Pekerjaan Plumbing',
      work_category: 'MEP',
      work_item_type: 'Plumbing',
      description: 'Instalasi, perbaikan, atau modifikasi pipa air bersih dan air kotor',
      is_master: true,
      created_date: '2026-01-01T08:10:00.000Z',
    },
    {
      id: 'work_item_master_004',
      work_item_name: 'Penggantian Flooring',
      work_category: 'Interior',
      work_item_type: 'Flooring',
      description: 'Penggantian material lantai: keramik, vinyl, parket, atau marmer',
      is_master: true,
      created_date: '2026-01-01T08:15:00.000Z',
    },
    {
      id: 'work_item_master_005',
      work_item_name: 'Pemasangan Partisi',
      work_category: 'Struktur',
      work_item_type: 'Partition',
      description: 'Pembuatan atau modifikasi dinding partisi gypsum atau bata ringan',
      is_master: true,
      created_date: '2026-01-01T08:20:00.000Z',
    },
    {
      id: 'work_item_master_006',
      work_item_name: 'Instalasi AC',
      work_category: 'MEP',
      work_item_type: 'HVAC',
      description: 'Pemasangan unit AC baru, relokasi, atau perbaikan instalasi',
      is_master: true,
      created_date: '2026-01-01T08:25:00.000Z',
    },
    {
      id: 'work_item_master_007',
      work_item_name: 'Kitchen Set & Lemari',
      work_category: 'Interior',
      work_item_type: 'Furniture',
      description: 'Pembuatan atau pemasangan kitchen set, lemari built-in, dan furniture custom lainnya',
      is_master: true,
      created_date: '2026-01-01T08:30:00.000Z',
    },
    {
      id: 'work_item_master_008',
      work_item_name: 'Waterproofing Kamar Mandi',
      work_category: 'Sipil',
      work_item_type: 'Waterproofing',
      description: 'Aplikasi lapisan waterproofing pada area basah seperti kamar mandi dan dapur',
      is_master: true,
      created_date: '2026-01-01T08:35:00.000Z',
    },
    {
      id: 'work_item_app_001',
      application_id: 'permit_001',
      work_item_name: 'Pengecatan Interior',
      work_category: 'Interior',
      work_item_type: 'General',
      description: 'Pengecatan ulang seluruh dinding kamar tidur utama dengan cat premium water-based',
      is_master: false,
      review_status: 'approved',
      created_date: '2026-04-05T08:00:00.000Z',
    },
    {
      id: 'work_item_app_002',
      application_id: 'permit_001',
      work_item_name: 'Penggantian Flooring',
      work_category: 'Interior',
      work_item_type: 'Flooring',
      description: 'Penggantian lantai lama dengan vinyl motif kayu premium di kamar tidur utama',
      is_master: false,
      review_status: 'approved',
      created_date: '2026-04-05T08:05:00.000Z',
    },
    {
      id: 'work_item_app_003',
      application_id: 'permit_001',
      work_item_name: 'Kitchen Set & Lemari',
      work_category: 'Interior',
      work_item_type: 'Furniture',
      description: 'Pemasangan lemari built-in custom di sisi dinding kanan kamar tidur utama',
      is_master: false,
      review_status: 'approved',
      created_date: '2026-04-05T08:10:00.000Z',
    },
    {
      id: 'work_item_app_004',
      application_id: 'permit_002',
      work_item_name: 'Instalasi Listrik',
      work_category: 'MEP',
      work_item_type: 'Electrical',
      description: 'Penambahan 4 stop kontak baru di area ruang kerja dan penggantian MCB panel listrik',
      is_master: false,
      review_status: 'pending',
      created_date: '2026-05-10T08:00:00.000Z',
    },
    {
      id: 'work_item_app_005',
      application_id: 'permit_003',
      work_item_name: 'Pekerjaan Plumbing',
      work_category: 'MEP',
      work_item_type: 'Plumbing',
      description: 'Perbaikan pipa air bersih bocor dan penggantian unit kloset kamar mandi',
      is_master: false,
      review_status: 'pending',
      created_date: '2026-05-08T09:00:00.000Z',
    },
  ],

  PermitRule: [
    {
      id: 'permit_rule_001',
      rule_name: 'Wajib menyerahkan fotokopi KTP kontraktor',
      permit_type: 'Renovation',
      is_master: true,
      is_mandatory: true,
      description: 'Identitas kontraktor harus terverifikasi sebelum pekerjaan dimulai',
      created_date: '2026-01-01T08:00:00.000Z',
    },
    {
      id: 'permit_rule_002',
      rule_name: 'Jam kerja: Senin-Sabtu pukul 08:00 - 17:00',
      permit_type: 'All',
      is_master: true,
      is_mandatory: true,
      description: 'Pekerjaan tidak boleh dilakukan di luar jam yang ditentukan untuk menghindari gangguan warga lain',
      created_date: '2026-01-01T08:05:00.000Z',
    },
    {
      id: 'permit_rule_003',
      rule_name: 'Dilarang menggunakan lift penumpang untuk angkut material',
      permit_type: 'All',
      is_master: true,
      is_mandatory: true,
      description: 'Seluruh material bangunan harus diangkut menggunakan lift servis',
      created_date: '2026-01-01T08:10:00.000Z',
    },
    {
      id: 'permit_rule_004',
      rule_name: 'Wajib menyerahkan daftar material yang digunakan',
      permit_type: 'Renovation',
      is_master: true,
      is_mandatory: true,
      description: 'Spesifikasi material harus disetujui manajemen sebelum pekerjaan dimulai',
      created_date: '2026-01-01T08:15:00.000Z',
    },
    {
      id: 'permit_rule_005',
      rule_name: 'Wajib memasang pelindung/cover di area kerja',
      permit_type: 'All',
      is_master: true,
      is_mandatory: true,
      description: 'Area sekitar pekerjaan harus dilindungi untuk mencegah kerusakan pada area umum',
      created_date: '2026-01-01T08:20:00.000Z',
    },
    {
      id: 'permit_rule_006',
      rule_name: 'Wajib membersihkan area kerja setelah selesai',
      permit_type: 'All',
      is_master: true,
      is_mandatory: false,
      description: 'Sisa material dan sampah pekerjaan harus dibuang pada tempat yang telah disediakan',
      created_date: '2026-01-01T08:25:00.000Z',
    },
  ],

  Reward: [
    {
      id: 'reward_001',
      title: 'Voucher Kopi Gratis',
      name: 'Voucher Kopi Gratis',
      points_required: 100,
      is_active: true,
      stock: 50,
      image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=900&q=80',
      description: 'Nikmati 1 cup kopi pilihan di Kopi Network. Berlaku untuk semua menu minuman ukuran regular.',
      valid_for_days: 30,
      valid_days: 30,
      category: 'Food & Beverage',
      merchant_name: 'Kopi Network',
      merchant_location: 'Food Avenue, Unit A-01, Ground Floor',
      terms: 'Berlaku untuk 1 minuman regular (exclude add-on). Tidak dapat digabung dengan promo lain. Tunjukkan kode voucher sebelum memesan.',
      created_date: '2026-01-20T08:00:00.000Z',
    },
    {
      id: 'reward_002',
      title: 'Tiket Bioskop (2 Seat)',
      name: 'Tiket Bioskop (2 Seat)',
      points_required: 500,
      is_active: true,
      stock: 20,
      image_url: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=900&q=80',
      description: 'Nikmati film pilihan bersama pasangan atau keluarga. Voucher berlaku untuk pembelian 2 tiket bioskop di ION Mall Cinema.',
      valid_for_days: 60,
      valid_days: 60,
      category: 'Entertainment',
      merchant_name: 'ION Mall Cinema',
      merchant_location: 'ION Mall, Lantai 3, Area A',
      terms: 'Berlaku untuk semua film reguler. Tidak berlaku untuk premiere dan special screening. Pemesanan via konter tiket.',
      created_date: '2026-01-21T08:00:00.000Z',
    },
    {
      id: 'reward_003',
      title: 'Day Pass Gym Iron Fitness',
      name: 'Day Pass Gym Iron Fitness',
      points_required: 150,
      is_active: true,
      stock: 30,
      image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=900&q=80',
      description: 'Akses penuh selama 1 hari ke seluruh fasilitas Iron Fitness Gym termasuk semua kelas group fitness.',
      valid_for_days: 30,
      valid_days: 30,
      category: 'Health & Fitness',
      merchant_name: 'Iron Fitness Gym',
      merchant_location: 'Sport Complex, Lantai 1, Area D',
      terms: 'Berlaku 1 kali masuk. Termasuk akses kelas group fitness yang tersedia di hari yang sama. Tidak dapat dipindahtangankan.',
      created_date: '2026-01-22T08:00:00.000Z',
    },
    {
      id: 'reward_004',
      title: 'Voucher Belanja ION Supermarket Rp 50K',
      name: 'Voucher Belanja ION Supermarket Rp 50K',
      points_required: 200,
      is_active: true,
      stock: 100,
      image_url: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=900&q=80',
      description: 'Voucher belanja senilai Rp 50.000 di ION Supermarket. Tidak berlaku untuk produk rokok dan minuman beralkohol.',
      valid_for_days: 45,
      valid_days: 45,
      category: 'Shopping',
      merchant_name: 'ION Supermarket',
      merchant_location: 'ION Mall, Ground Floor, Area A',
      terms: 'Minimum transaksi Rp 100.000. Tidak berlaku untuk rokok, minuman beralkohol, dan pulsa. Satu kode per transaksi.',
      created_date: '2026-01-23T08:00:00.000Z',
    },
    {
      id: 'reward_005',
      title: 'Parkir Gratis 1 Bulan',
      name: 'Parkir Gratis 1 Bulan',
      points_required: 800,
      is_active: true,
      stock: 10,
      image_url: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=900&q=80',
      description: 'Akses parkir gratis selama 1 bulan penuh untuk 1 kendaraan roda 4. Akan diaktifkan mulai tanggal berikutnya setelah klaim.',
      valid_for_days: 30,
      valid_days: 30,
      category: 'Facility',
      merchant_name: 'ION Parking Management',
      merchant_location: 'Basement Parkir, Damai Putra Residence',
      terms: 'Berlaku untuk 1 plat nomor kendaraan yang terdaftar. Aktivasi H+1 setelah klaim. Tidak dapat dipindahtangankan.',
      created_date: '2026-01-24T08:00:00.000Z',
    },
    {
      id: 'reward_006',
      title: 'Voucher Makan Rasa Nusantara Rp 100K',
      name: 'Voucher Makan Rasa Nusantara Rp 100K',
      points_required: 350,
      is_active: true,
      stock: 40,
      image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=80',
      description: 'Voucher makan senilai Rp 100.000 di restoran Rasa Nusantara. Berlaku untuk makan di tempat (dine-in) minimal transaksi Rp 150.000.',
      valid_for_days: 30,
      valid_days: 30,
      category: 'Food & Beverage',
      merchant_name: 'Rasa Nusantara',
      merchant_location: 'Food Avenue, Unit B-02, Ground Floor',
      terms: 'Minimum transaksi Rp 150.000. Hanya berlaku dine-in. Tidak dapat digabung dengan promo lain. Satu kode per meja.',
      created_date: '2026-01-25T08:00:00.000Z',
    },
    {
      id: 'reward_007',
      title: 'Paket Spa Serene 60 Menit',
      name: 'Paket Spa Serene 60 Menit',
      points_required: 600,
      is_active: true,
      stock: 15,
      image_url: 'https://images.unsplash.com/photo-1552693673-1bf958298935?w=900&q=80',
      description: 'Paket perawatan spa 60 menit di Serene Spa & Salon. Pilihan: Swedish massage, aromatherapy, atau hot stone therapy.',
      valid_for_days: 60,
      valid_days: 60,
      category: 'Health & Beauty',
      merchant_name: 'Serene Spa & Salon',
      merchant_location: 'Wellness Center, Level 2, Area E',
      terms: 'Booking minimal H-1 via aplikasi ION. Pilih treatment: Swedish massage, aromatherapy, atau hot stone. Tidak berlaku akhir pekan dan hari libur nasional.',
      created_date: '2026-01-26T08:00:00.000Z',
    },
    {
      id: 'reward_008',
      title: 'Voucher Artisan Bakery Rp 75K',
      name: 'Voucher Artisan Bakery Rp 75K',
      points_required: 250,
      is_active: true,
      stock: 60,
      image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=900&q=80',
      description: 'Voucher senilai Rp 75.000 untuk berbelanja di Artisan Bakery. Pilih dari ratusan varian roti dan kue segar.',
      valid_for_days: 30,
      valid_days: 30,
      category: 'Food & Beverage',
      merchant_name: 'Artisan Bakery',
      merchant_location: 'Food Avenue, Unit F-06, Ground Floor',
      terms: 'Berlaku untuk semua produk kecuali paket khusus dan pre-order. Tidak dapat dikembalikan dalam bentuk uang tunai. Satu kode per transaksi.',
      created_date: '2026-01-27T08:00:00.000Z',
    },
  ],

  UserPoints: [
    {
      id: 'points_001',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      balance: 850,
      lifetime_points: 2350,
      total_earned: 2350,
      total_redeemed: 1500,
      created_date: '2026-01-20T08:00:00.000Z',
    },
    {
      id: 'points_002',
      user_email: 'sari@example.com',
      user_name: 'Sari Dewi Anggraini',
      balance: 420,
      lifetime_points: 820,
      total_earned: 820,
      total_redeemed: 400,
      created_date: '2026-01-20T08:00:00.000Z',
    },
  ],

  Lottery: [
    {
      id: 'lottery_001',
      title: 'Resident Lucky Draw Bulanan',
      name: 'Resident Lucky Draw Bulanan',
      description: 'Undian bulanan eksklusif untuk seluruh warga ION. Hadiah utama: Smart TV 55 inch, Voucher Belanja Rp 2 juta, dan berbagai hadiah menarik lainnya.',
      is_active: true,
      points_cost: 50,
      points_per_entry: 50,
      max_entries_per_user: 10,
      total_entries: 342,
      prize_1: 'Smart TV Samsung 55 inch',
      prize_2: 'Voucher Belanja Rp 2.000.000',
      prize_3: 'Paket Spa Premium',
      prizes: [
        { rank: 1, name: 'Smart TV Samsung 55 inch', value: 8000000 },
        { rank: 2, name: 'Voucher Belanja Rp 2.000.000', value: 2000000 },
        { rank: 3, name: 'Paket Spa Serene Premium', value: 800000 },
        { rank: 4, name: 'Voucher Makan Rp 500.000 (5 pemenang)', value: 500000 },
      ],
      start_date: '2026-05-01',
      end_date: '2026-05-30',
      draw_date: '2026-05-31',
      winner_announced: false,
      image_url: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=900&q=80',
      created_date: '2026-02-20T08:00:00.000Z',
    },
    {
      id: 'lottery_002',
      title: 'Grand Prize Anniversary ION',
      name: 'Grand Prize Anniversary ION',
      description: 'Undian spesial dalam rangka ulang tahun ke-4 ION Network. Hadiah utama perjalanan wisata ke Bali selama 4 hari 3 malam untuk 2 orang!',
      is_active: true,
      points_cost: 100,
      points_per_entry: 100,
      max_entries_per_user: 5,
      total_entries: 178,
      prize_1: 'Liburan Bali 4D3N untuk 2 Orang',
      prize_2: 'iPhone 16 Pro',
      prize_3: 'Voucher Belanja Rp 5.000.000',
      prizes: [
        { rank: 1, name: 'Liburan Bali 4D3N untuk 2 Orang', value: 15000000 },
        { rank: 2, name: 'iPhone 16 Pro 256GB', value: 18000000 },
        { rank: 3, name: 'Voucher Belanja Rp 5.000.000', value: 5000000 },
        { rank: 4, name: 'Samsung Galaxy Watch 7 (3 pemenang)', value: 3500000 },
      ],
      start_date: '2026-06-01',
      end_date: '2026-06-29',
      draw_date: '2026-06-30',
      winner_announced: false,
      image_url: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=900&q=80',
      created_date: '2026-03-01T08:00:00.000Z',
    },
    {
      id: 'lottery_003',
      title: 'Flash Draw Hari Kemerdekaan',
      name: 'Flash Draw Hari Kemerdekaan',
      description: 'Undian kilat spesial 17 Agustus. Hanya berlangsung 1 minggu! Hadiah: sepeda listrik, voucher makan, dan ratusan hadiah hiburan.',
      is_active: false,
      points_cost: 25,
      points_per_entry: 25,
      max_entries_per_user: 20,
      total_entries: 890,
      prize_1: 'Sepeda Listrik Polygon',
      prize_2: 'JBL Bluetooth Speaker',
      prize_3: 'Voucher Makan Rp 500.000',
      prizes: [
        { rank: 1, name: 'Sepeda Listrik Polygon E-Bike', value: 7500000 },
        { rank: 2, name: 'JBL Xtreme 3 Bluetooth Speaker', value: 2500000 },
        { rank: 3, name: 'Voucher Makan Rp 500.000 (10 pemenang)', value: 500000 },
        { rank: 4, name: 'Merchandise ION Exclusive Pack (50 pemenang)', value: 150000 },
      ],
      start_date: '2026-08-10',
      end_date: '2026-08-16',
      draw_date: '2026-08-17',
      winner_announced: true,
      winner_name: 'Andi Kurniawan',
      winner_email: 'andi@example.com',
      winner_prize: 'Sepeda Listrik Polygon E-Bike',
      image_url: 'https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=900&q=80',
      created_date: '2026-04-01T08:00:00.000Z',
    },
  ],

  Notification: [
    {
      id: 'notification_001',
      user_email: 'resident@example.com',
      title: 'Selamat Datang di ION Network!',
      message: 'Aplikasi resident Anda sudah aktif. Mulai eksplorasi fasilitas, kirim tiket, klaim reward, dan tetap terhubung dengan komunitas.',
      read: true,
      type: 'info',
      created_date: '2026-01-05T08:00:00.000Z',
    },
    {
      id: 'notification_002',
      user_email: 'resident@example.com',
      title: 'Tiket #TCK-2026-0002 sedang diproses',
      message: 'Laporan kebocoran pipa Anda sedang ditangani oleh Tim Teknik. Teknisi akan hadir hari ini antara pukul 13:00 - 15:00.',
      read: false,
      type: 'ticket',
      related_id: 'ticket_002',
      created_date: '2026-04-29T09:00:00.000Z',
    },
    {
      id: 'notification_003',
      user_email: 'resident@example.com',
      title: 'Izin Renovasi PRM-2026-0001 Disetujui',
      message: 'Pengajuan izin renovasi unit A-1508 Anda telah disetujui. Pekerjaan dapat dimulai sesuai jadwal pada 15 Mei 2026.',
      read: false,
      type: 'permit',
      related_id: 'permit_001',
      created_date: '2026-04-10T10:30:00.000Z',
    },
    {
      id: 'notification_004',
      user_email: 'resident@example.com',
      title: 'Event: Yoga Pagi Bersama dimulai besok!',
      message: 'Jangan lupa! Program Yoga Pagi Bersama mulai besok Senin 12 Mei 2026 pukul 06:30 di Central Park. Bawa matras dan pakaian nyaman.',
      read: false,
      type: 'event',
      related_id: 'event_005',
      created_date: '2026-05-11T18:00:00.000Z',
    },
    {
      id: 'notification_005',
      user_email: 'resident@example.com',
      title: 'Poin Anda bertambah 200 poin!',
      message: 'Selamat! Anda mendapatkan 200 poin dari scan struk pembelian di ION Supermarket. Total saldo poin Anda sekarang: 850 poin.',
      read: true,
      type: 'points',
      created_date: '2026-05-08T14:00:00.000Z',
    },
    {
      id: 'notification_006',
      user_email: 'resident@example.com',
      title: 'Jadwal Pembersihan Tangki Air Tower A',
      message: 'Pemberitahuan: Pembersihan tangki air Tower A akan dilaksanakan Sabtu, 17 Mei 2026 pukul 08:00 - 12:00. Air akan dimatikan sementara pada jam tersebut.',
      read: false,
      type: 'announcement',
      created_date: '2026-05-12T07:00:00.000Z',
    },
    {
      id: 'notification_007',
      user_email: 'resident@example.com',
      title: 'Pembayaran IPL Mei 2026 Jatuh Tempo',
      message: 'Pengingat: Pembayaran IPL bulan Mei 2026 sebesar Rp 450.000 jatuh tempo pada 15 Mei 2026. Bayar sekarang melalui menu Pembayaran di aplikasi.',
      read: false,
      type: 'payment',
      created_date: '2026-05-10T08:00:00.000Z',
    },
    {
      id: 'notification_008',
      user_email: 'resident@example.com',
      title: 'Undian Lucky Draw - Daftarkan diri Anda!',
      message: 'Resident Lucky Draw Bulanan masih terbuka! Tukarkan 50 poin untuk 1 tiket undian. Hadiah utama Smart TV 55 inch menanti. Pengundian 31 Mei 2026.',
      read: true,
      type: 'lottery',
      related_id: 'lottery_001',
      created_date: '2026-05-01T09:00:00.000Z',
    },
  ],

  DepositRefundRequest: [
    {
      id: 'refund_001',
      refund_request_number: 'RFD-2026-0001',
      unit_id: 'unit_002',
      unit_number: 'B-0902',
      cluster_name: 'Sayana',
      block_number: 'B',
      user_email: 'resident@example.com',
      applicant_name: 'Budi Santoso',
      ktp_number: '3275011504900001',
      phone_number: '0812-3456-7890',
      email: 'resident@example.com',
      refund_reason: 'Masa sewa telah berakhir dan tidak diperpanjang. Pindah ke unit milik sendiri di tower A. Unit telah dikosongkan dan dikembalikan dalam kondisi baik.',
      original_deposit_amount: 13000000,
      deduction_amount: 500000,
      approved_refund_amount: 12500000,
      bank_name: 'BCA',
      bank_account_number: '1234567890',
      bank_account_holder_name: 'Budi Santoso',
      refund_status: 'Waiting Finance Validation',
      move_out_date: '2026-04-30',
      created_date: '2026-05-02T09:00:00.000Z',
    },
    {
      id: 'refund_002',
      refund_request_number: 'RFD-2026-0002',
      unit_id: 'unit_003',
      unit_number: 'C-0712',
      cluster_name: 'Green Valley',
      block_number: 'C',
      user_email: 'sari@example.com',
      applicant_name: 'Sari Dewi Anggraini',
      ktp_number: '3275015508950002',
      phone_number: '0813-9876-5432',
      email: 'sari@example.com',
      refund_reason: 'Pindah domisili ke luar kota karena penempatan kerja. Semua kewajiban sudah diselesaikan.',
      original_deposit_amount: 12000000,
      deduction_amount: 0,
      bank_name: 'Mandiri',
      bank_account_number: '1110002223334',
      bank_account_holder_name: 'Sari Dewi Anggraini',
      refund_status: 'Submitted',
      move_out_date: '2026-05-15',
      created_date: '2026-05-07T10:00:00.000Z',
    },
    {
      id: 'refund_003',
      refund_request_number: 'RFD-2026-0003',
      unit_id: 'unit_004',
      unit_number: 'D-0305',
      cluster_name: 'Damai Putra',
      block_number: 'D',
      user_email: 'andi@example.com',
      applicant_name: 'Andi Kurniawan',
      ktp_number: '3275019901000003',
      phone_number: '0878-1122-3344',
      email: 'andi@example.com',
      refund_reason: 'Pembatalan pembelian unit karena ketidaksesuaian spesifikasi dengan perjanjian awal.',
      original_deposit_amount: 8000000,
      deduction_amount: 800000,
      approved_refund_amount: 7200000,
      bank_name: 'BNI',
      bank_account_number: '9988776655',
      bank_account_holder_name: 'Andi Kurniawan',
      refund_status: 'Paid',
      move_out_date: '2026-04-15',
      payment_date: '2026-04-28',
      created_date: '2026-04-16T08:00:00.000Z',
    },
  ],

  RefundDocumentChecklist: [
    {
      id: 'rdoc_001',
      refund_request_id: 'refund_001',
      checklist_item_code: 'KTP',
      checklist_item_name: 'Fotokopi KTP Pemohon',
      is_submitted: true,
      verification_status: 'Verified',
      verifier_notes: 'Dokumen lengkap dan valid',
      created_date: '2026-05-02T09:01:00.000Z',
    },
    {
      id: 'rdoc_002',
      refund_request_id: 'refund_001',
      checklist_item_code: 'PERJANJIAN',
      checklist_item_name: 'Surat Perjanjian Sewa',
      is_submitted: true,
      verification_status: 'Verified',
      verifier_notes: 'Perjanjian sewa sesuai dan sudah expired',
      created_date: '2026-05-02T09:02:00.000Z',
    },
    {
      id: 'rdoc_003',
      refund_request_id: 'refund_001',
      checklist_item_code: 'BAST',
      checklist_item_name: 'BAST (Berita Acara Serah Terima) Unit',
      is_submitted: true,
      verification_status: 'Verified',
      verifier_notes: 'Unit sudah diserahterimakan dalam kondisi baik',
      created_date: '2026-05-02T09:03:00.000Z',
    },
    {
      id: 'rdoc_004',
      refund_request_id: 'refund_001',
      checklist_item_code: 'REKENING',
      checklist_item_name: 'Buku Rekening / Bukti Kepemilikan Rekening',
      is_submitted: true,
      verification_status: 'Verified',
      created_date: '2026-05-02T09:04:00.000Z',
    },
    {
      id: 'rdoc_005',
      refund_request_id: 'refund_002',
      checklist_item_code: 'KTP',
      checklist_item_name: 'Fotokopi KTP Pemohon',
      is_submitted: true,
      verification_status: 'Pending',
      created_date: '2026-05-07T10:01:00.000Z',
    },
    {
      id: 'rdoc_006',
      refund_request_id: 'refund_002',
      checklist_item_code: 'PERJANJIAN',
      checklist_item_name: 'Surat Perjanjian Sewa',
      is_submitted: true,
      verification_status: 'Pending',
      created_date: '2026-05-07T10:02:00.000Z',
    },
    {
      id: 'rdoc_007',
      refund_request_id: 'refund_002',
      checklist_item_code: 'BAST',
      checklist_item_name: 'BAST (Berita Acara Serah Terima) Unit',
      is_submitted: false,
      verification_status: 'Pending',
      created_date: '2026-05-07T10:03:00.000Z',
    },
    {
      id: 'rdoc_008',
      refund_request_id: 'refund_002',
      checklist_item_code: 'REKENING',
      checklist_item_name: 'Buku Rekening / Bukti Kepemilikan Rekening',
      is_submitted: true,
      verification_status: 'Pending',
      created_date: '2026-05-07T10:04:00.000Z',
    },
  ],

  DepositInspectionClearance: [
    {
      id: 'inspection_clearance_001',
      refund_request_id: 'refund_001',
      inspector_name: 'Hendra Wijaya',
      inspection_date: '2026-05-05',
      inspection_result: 'Minor Damage',
      deduction_amount: 500000,
      room_conditions: 'Kondisi unit secara keseluruhan baik. Ditemukan goresan cat di dinding kamar mandi dan engsel pintu kamar yang longgar.',
      furniture_conditions: 'Semua furnitur bawaan dalam kondisi baik.',
      notes: 'Deduction Rp 500.000 untuk biaya pengecatan ulang kamar mandi.',
      activity_description: 'Inspeksi dilaksanakan. Hasil: Minor Damage. Deduksi: IDR 500.000',
      performed_by: 'Hendra Wijaya',
      created_date: '2026-05-05T14:00:00.000Z',
    },
    {
      id: 'inspection_clearance_002',
      refund_request_id: 'refund_003',
      inspector_name: 'Rizky Pratama',
      inspection_date: '2026-04-18',
      inspection_result: 'Minor Damage',
      deduction_amount: 800000,
      room_conditions: 'Beberapa keramik pecah di kamar mandi dan noda di karpet ruang tamu yang tidak bisa dibersihkan.',
      furniture_conditions: 'Furnitur bawaan lengkap dan dalam kondisi baik.',
      notes: 'Deduction Rp 800.000 untuk penggantian keramik dan pembersihan karpet profesional.',
      activity_description: 'Inspeksi dilaksanakan. Hasil: Minor Damage. Deduksi: IDR 800.000',
      performed_by: 'Rizky Pratama',
      created_date: '2026-04-18T11:00:00.000Z',
    },
  ],

  RefundApprovalWorkflow: [
    {
      id: 'rwf_001',
      refund_request_id: 'refund_001',
      stage: 'verification',
      stage_label: 'Verifikasi Dokumen',
      approved_by: 'Tim Verifikasi',
      approved_at: '2026-05-04T10:00:00.000Z',
      comment: 'Semua dokumen sudah diverifikasi dan lengkap.',
      status: 'approved',
      created_date: '2026-05-04T10:00:00.000Z',
    },
    {
      id: 'rwf_002',
      refund_request_id: 'refund_001',
      stage: 'inspection',
      stage_label: 'Inspeksi Unit',
      approved_by: 'Hendra Wijaya',
      approved_at: '2026-05-05T14:30:00.000Z',
      comment: 'Inspeksi selesai. Ditemukan kerusakan minor, deduction Rp 500.000.',
      status: 'approved',
      created_date: '2026-05-05T14:30:00.000Z',
    },
    {
      id: 'rwf_003',
      refund_request_id: 'refund_003',
      stage: 'verification',
      stage_label: 'Verifikasi Dokumen',
      approved_by: 'Tim Verifikasi',
      approved_at: '2026-04-17T09:00:00.000Z',
      comment: 'Dokumen lengkap dan valid.',
      status: 'approved',
      created_date: '2026-04-17T09:00:00.000Z',
    },
    {
      id: 'rwf_004',
      refund_request_id: 'refund_003',
      stage: 'inspection',
      stage_label: 'Inspeksi Unit',
      approved_by: 'Rizky Pratama',
      approved_at: '2026-04-18T11:30:00.000Z',
      comment: 'Inspeksi selesai. Deduction Rp 800.000.',
      status: 'approved',
      created_date: '2026-04-18T11:30:00.000Z',
    },
    {
      id: 'rwf_005',
      refund_request_id: 'refund_003',
      stage: 'finance',
      stage_label: 'Validasi Finance',
      approved_by: 'Tim Finance',
      approved_at: '2026-04-22T10:00:00.000Z',
      comment: 'Jumlah refund sudah divalidasi: Rp 7.200.000.',
      status: 'approved',
      created_date: '2026-04-22T10:00:00.000Z',
    },
    {
      id: 'rwf_006',
      refund_request_id: 'refund_003',
      stage: 'payment',
      stage_label: 'Pembayaran',
      approved_by: 'Tim Finance',
      approved_at: '2026-04-28T14:00:00.000Z',
      comment: 'Transfer berhasil. Rp 7.200.000 dikirim ke rekening BNI atas nama Andi Kurniawan.',
      status: 'approved',
      created_date: '2026-04-28T14:00:00.000Z',
    },
  ],

  RefundLedger: [
    {
      id: 'rledger_001',
      refund_request_id: 'refund_003',
      transaction_type: 'Refund Payment',
      amount: 7200000,
      description: 'Transfer deposit refund ke rekening BNI atas nama Andi Kurniawan',
      reference_number: 'TRF-2026-04280001',
      performed_by: 'Tim Finance',
      created_date: '2026-04-28T14:00:00.000Z',
    },
  ],

  RefundActivityLog: [
    {
      id: 'ralog_001',
      refund_request_id: 'refund_001',
      activity_description: 'Pengajuan refund dibuat oleh Budi Santoso',
      performed_by: 'Budi Santoso',
      created_date: '2026-05-02T09:00:00.000Z',
    },
    {
      id: 'ralog_002',
      refund_request_id: 'refund_001',
      activity_description: 'Pengajuan diterima untuk diproses verifikasi dokumen',
      performed_by: 'Sistem',
      created_date: '2026-05-02T09:05:00.000Z',
    },
    {
      id: 'ralog_003',
      refund_request_id: 'refund_001',
      activity_description: 'Verifikasi dokumen selesai. Semua dokumen valid. Status: Waiting Inspection Result',
      performed_by: 'Tim Verifikasi',
      created_date: '2026-05-04T10:00:00.000Z',
    },
    {
      id: 'ralog_004',
      refund_request_id: 'refund_001',
      activity_description: 'Inspeksi unit dilaksanakan oleh Hendra Wijaya. Hasil: Minor Damage. Deduction: IDR 500.000. Status: Waiting Finance Validation',
      performed_by: 'Hendra Wijaya',
      created_date: '2026-05-05T14:30:00.000Z',
    },
    {
      id: 'ralog_005',
      refund_request_id: 'refund_002',
      activity_description: 'Pengajuan refund dibuat oleh Sari Dewi Anggraini',
      performed_by: 'Sari Dewi Anggraini',
      created_date: '2026-05-07T10:00:00.000Z',
    },
    {
      id: 'ralog_006',
      refund_request_id: 'refund_003',
      activity_description: 'Pengajuan refund dibuat oleh Andi Kurniawan',
      performed_by: 'Andi Kurniawan',
      created_date: '2026-04-16T08:00:00.000Z',
    },
    {
      id: 'ralog_007',
      refund_request_id: 'refund_003',
      activity_description: 'Refund berhasil dibayarkan sebesar IDR 7.200.000 ke rekening BNI Andi Kurniawan',
      performed_by: 'Tim Finance',
      created_date: '2026-04-28T14:00:00.000Z',
    },
  ],

  ActivityLog: [
    {
      id: 'alog_001',
      application_id: 'permit_001',
      action: 'status_change',
      performed_by: 'Rizky Pratama',
      old_value: 'Submitted',
      new_value: 'approved',
      note: 'Izin renovasi disetujui setelah verifikasi dokumen dan survei lapangan. Pekerjaan dapat dimulai sesuai jadwal.',
      created_date: '2026-04-10T10:00:00.000Z',
    },
    {
      id: 'alog_002',
      application_id: 'permit_002',
      action: 'status_change',
      performed_by: 'Admin',
      old_value: 'Draft',
      new_value: 'Submitted',
      note: 'Pengajuan izin pekerjaan listrik diterima untuk ditindaklanjuti.',
      created_date: '2026-05-10T08:30:00.000Z',
    },
    {
      id: 'alog_003',
      application_id: 'permit_003',
      action: 'status_change',
      performed_by: 'Admin',
      old_value: 'Submitted',
      new_value: 'inspection_required',
      note: 'Diperlukan survei lapangan sebelum izin dapat diberikan untuk pekerjaan plumbing.',
      created_date: '2026-05-09T11:00:00.000Z',
    },
    {
      id: 'alog_004',
      application_id: 'permit_004',
      action: 'status_change',
      performed_by: 'Rizky Pratama',
      old_value: 'Submitted',
      new_value: 'rejected',
      note: 'Partisi permanen tidak diperbolehkan sesuai regulasi bangunan.',
      created_date: '2026-05-03T14:00:00.000Z',
    },
  ],

  ApprovalWorkflow: [
    {
      id: 'awf_001',
      application_id: 'permit_001',
      workflow_stage: 'document_check',
      performed_by: 'Admin',
      action: 'Approve',
      comment: 'Dokumen lengkap: KTP kontraktor, daftar material, dan jadwal kerja sudah diterima.',
      created_date: '2026-04-07T09:00:00.000Z',
    },
    {
      id: 'awf_002',
      application_id: 'permit_001',
      workflow_stage: 'building_infrastructure_review',
      performed_by: 'Tim Teknis',
      action: 'Approve',
      comment: 'Survei lapangan selesai. Pekerjaan yang direncanakan tidak berisiko terhadap struktur bangunan.',
      created_date: '2026-04-08T14:00:00.000Z',
    },
    {
      id: 'awf_003',
      application_id: 'permit_001',
      workflow_stage: 'head_approval',
      performed_by: 'Rizky Pratama',
      action: 'Approve',
      comment: 'Disetujui. Harap memastikan semua aturan kerja dipatuhi, terutama jam operasional dan penggunaan lift servis.',
      created_date: '2026-04-10T10:00:00.000Z',
    },
    {
      id: 'awf_004',
      application_id: 'permit_004',
      workflow_stage: 'head_approval',
      performed_by: 'Rizky Pratama',
      action: 'Reject',
      comment: 'Ditolak karena partisi permanen melanggar peraturan bangunan pasal 7 ayat 2.',
      created_date: '2026-05-03T14:00:00.000Z',
    },
  ],

  Inspection: [
    {
      id: 'insp_001',
      application_id: 'permit_001',
      inspection_date: '2026-04-08',
      inspection_type: 'Pre-Work Survey',
      inspector: 'Tim Teknis - Baskoro',
      inspector_name: 'Baskoro Wibowo',
      result: 'Passed',
      findings: 'Unit dalam kondisi baik. Rencana renovasi tidak membahayakan struktur bangunan. Kontraktor CV Jaya Konstruksi sudah terverifikasi.',
      site_condition: 'Baik — tidak ada kerusakan struktural pada dinding dan lantai eksisting',
      issue_found: 'Tidak ada masalah signifikan yang ditemukan',
      corrective_action: 'Tidak diperlukan tindakan korektif',
      status: 'completed',
      created_date: '2026-04-08T14:00:00.000Z',
    },
    {
      id: 'insp_002',
      application_id: 'permit_003',
      inspection_date: '2026-05-14',
      inspection_type: 'MEP Inspection',
      inspector: 'Tim MEP - Sapto',
      inspector_name: 'Sapto Nugroho',
      result: 'Scheduled',
      findings: 'Jadwal inspeksi sudah dikonfirmasi. Tim MEP akan meninjau kondisi instalasi plumbing eksisting.',
      site_condition: 'Belum diinspeksi',
      issue_found: 'Perlu diverifikasi kondisi pipa eksisting sebelum pekerjaan dimulai',
      corrective_action: 'Menunggu hasil inspeksi lapangan',
      status: 'scheduled',
      created_date: '2026-05-09T11:00:00.000Z',
    },
  ],

  PermitDocument: [
    {
      id: 'pdoc_001',
      application_id: 'permit_001',
      document_name: 'KTP Kontraktor - CV Jaya Konstruksi',
      document_type: 'KTP',
      file_url: 'https://example.com/docs/ktp_jaya.pdf',
      version_number: 1,
      uploaded_by: 'Budi Santoso',
      verification_status: 'verified',
      created_date: '2026-04-05T08:30:00.000Z',
    },
    {
      id: 'pdoc_002',
      application_id: 'permit_001',
      document_name: 'Daftar Material Renovasi',
      document_type: 'Material List',
      file_url: 'https://example.com/docs/material_list.pdf',
      version_number: 1,
      uploaded_by: 'Budi Santoso',
      verification_status: 'verified',
      created_date: '2026-04-05T08:35:00.000Z',
    },
    {
      id: 'pdoc_003',
      application_id: 'permit_001',
      document_name: 'Denah Rencana Renovasi',
      document_type: 'Floor Plan',
      file_url: 'https://example.com/docs/floor_plan.pdf',
      version_number: 2,
      uploaded_by: 'Budi Santoso',
      verification_status: 'verified',
      created_date: '2026-04-05T08:40:00.000Z',
    },
    {
      id: 'pdoc_004',
      application_id: 'permit_002',
      document_name: 'KTP Kontraktor - PT Listrik Mandiri',
      document_type: 'KTP',
      file_url: 'https://example.com/docs/ktp_listrik.pdf',
      version_number: 1,
      uploaded_by: 'Budi Santoso',
      verification_status: 'pending',
      created_date: '2026-05-10T08:30:00.000Z',
    },
    {
      id: 'pdoc_005',
      application_id: 'permit_002',
      document_name: 'Sertifikasi Kelistrikan Kontraktor',
      document_type: 'Certificate',
      file_url: 'https://example.com/docs/cert_electric.pdf',
      version_number: 1,
      uploaded_by: 'Budi Santoso',
      verification_status: 'pending',
      created_date: '2026-05-10T08:35:00.000Z',
    },
    {
      id: 'pdoc_006',
      application_id: 'permit_003',
      document_name: 'KTP Kontraktor - UD Berkah Plumbing',
      document_type: 'KTP',
      file_url: 'https://example.com/docs/ktp_berkah.pdf',
      version_number: 1,
      uploaded_by: 'Budi Santoso',
      verification_status: 'pending',
      created_date: '2026-05-08T09:30:00.000Z',
    },
  ],

  RewardClaim: [
    {
      id: 'rclaim_001',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      reward_id: 'reward_001',
      reward_title: 'Voucher Kopi Gratis',
      reward_image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=900&q=80',
      merchant_name: 'Kopi Network',
      merchant_location: 'Food Avenue, Unit A-01, Ground Floor',
      points_used: 100,
      status: 'used',
      claim_code: 'IONKOPI-A1B2C3',
      claim_date: '2026-04-15',
      expiry_date: '2026-05-15',
      used_at: '2026-04-20T10:00:00.000Z',
      created_date: '2026-04-15T14:00:00.000Z',
    },
    {
      id: 'rclaim_002',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      reward_id: 'reward_003',
      reward_title: 'Day Pass Gym Iron Fitness',
      reward_image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=900&q=80',
      merchant_name: 'Iron Fitness Gym',
      merchant_location: 'Sport Complex, Lantai 1, Area D',
      points_used: 150,
      status: 'active',
      claim_code: 'IONGYM-D4E5F6',
      claim_date: '2026-05-11',
      expiry_date: '2026-06-10',
      valid_until: '2026-06-10',
      created_date: '2026-05-11T09:00:00.000Z',
    },
    {
      id: 'rclaim_003',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      reward_id: 'reward_004',
      reward_title: 'Voucher Belanja ION Supermarket Rp 50K',
      reward_image_url: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=900&q=80',
      merchant_name: 'ION Supermarket',
      merchant_location: 'ION Mall, Ground Floor, Area A',
      points_used: 200,
      status: 'active',
      claim_code: 'IONSUP-G7H8I9',
      claim_date: '2026-05-11',
      expiry_date: '2026-06-25',
      valid_until: '2026-06-25',
      created_date: '2026-05-11T09:05:00.000Z',
    },
    {
      id: 'rclaim_004',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      reward_id: 'reward_006',
      reward_title: 'Voucher Makan Rasa Nusantara Rp 100K',
      reward_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=80',
      merchant_name: 'Rasa Nusantara',
      merchant_location: 'Food Avenue, Unit B-02, Ground Floor',
      points_used: 350,
      status: 'expired',
      claim_code: 'IONNAS-J0K1L2',
      claim_date: '2026-03-15',
      expiry_date: '2026-04-14',
      created_date: '2026-03-15T11:00:00.000Z',
    },
  ],

  ScannedReceipt: [
    {
      id: 'receipt_001',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      merchant_name: 'ION Supermarket',
      merchant_address: 'ION Mall, Ground Floor, Area A, Damai Putra Residence',
      receipt_number: 'INV-SUP-20260508-0042',
      transaction_date: '2026-05-08',
      scan_date: '2026-05-08',
      total_amount: 185000,
      points_earned: 185,
      status: 'approved',
      image_url: 'https://images.unsplash.com/photo-1532372320978-9b4b0c74e24d?w=900&q=80',
      receipt_image_url: 'https://images.unsplash.com/photo-1532372320978-9b4b0c74e24d?w=900&q=80',
      ocr_raw_text: 'ION Supermarket\nGround Floor ION Mall\nDate: 08/05/2026\nCashier: Rina\n\nBeras Premium 5kg     75.000\nMinyak Goreng 2L      35.000\nSabun Mandi 3pcs      18.000\nMinuman Sari Buah     12.000\nSusu UHT Full Cream   45.000\n\nSubtotal:            185.000\nTotal:               185.000\nTunai:               200.000\nKembalian:            15.000\n\nTerima kasih telah berbelanja!',
      created_date: '2026-05-08T14:00:00.000Z',
    },
    {
      id: 'receipt_002',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      merchant_name: 'Kopi Network',
      merchant_address: 'Food Avenue, Unit A-01, Ground Floor, Damai Putra Residence',
      receipt_number: 'KPN-20260506-0118',
      transaction_date: '2026-05-06',
      scan_date: '2026-05-06',
      total_amount: 45000,
      points_earned: 45,
      status: 'approved',
      image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=900&q=80',
      receipt_image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=900&q=80',
      ocr_raw_text: 'Kopi Network\nFood Avenue Unit A-01\nDate: 06/05/2026 10:22\n\nFlat White              35.000\nCroissant Plain         10.000\n\nSubtotal:               45.000\nTotal:                  45.000\n\nThank you! See you again.',
      created_date: '2026-05-06T10:30:00.000Z',
    },
    {
      id: 'receipt_003',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      merchant_name: 'Artisan Bakery',
      merchant_address: 'Food Avenue, Unit F-06, Ground Floor, Damai Putra Residence',
      receipt_number: 'ART-20260504-0055',
      transaction_date: '2026-05-04',
      scan_date: '2026-05-04',
      total_amount: 120000,
      points_earned: 0,
      status: 'pending',
      image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=900&q=80',
      receipt_image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=900&q=80',
      ocr_raw_text: 'Artisan Bakery\nFood Avenue Unit F-06\nDate: 04/05/2026\n\nSourdough Loaf         45.000\nCroissant Butter 2pcs  30.000\nPain au Chocolat       25.000\nDanish Fruit           20.000\n\nSubtotal:             120.000\nTotal:                120.000',
      created_date: '2026-05-04T08:45:00.000Z',
    },
    {
      id: 'receipt_004',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      merchant_name: 'Rasa Nusantara',
      merchant_address: 'Food Avenue, Unit B-02, Ground Floor, Damai Putra Residence',
      receipt_number: 'RN-20260428-0077',
      transaction_date: '2026-04-28',
      scan_date: '2026-04-28',
      total_amount: 250000,
      points_earned: 250,
      status: 'approved',
      image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=80',
      receipt_image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&q=80',
      ocr_raw_text: 'Rasa Nusantara\nFood Avenue Unit B-02\nDate: 28/04/2026 12:45\nMeja: 07 / 2 orang\n\nRendang Padang         85.000\nSoto Betawi            65.000\nNasi Putih 2x          20.000\nTeh Manis Panas 2x     16.000\nEs Campur              20.000\nKerupuk                 5.000\nPajak 10%              21.000\nService 5%             10.500\n\nTotal:                242.500\nPembulatan:             7.500\nGrand Total:          250.000',
      created_date: '2026-04-28T13:00:00.000Z',
    },
    {
      id: 'receipt_005',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      merchant_name: 'ION Supermarket',
      merchant_address: 'ION Mall, Ground Floor, Area A, Damai Putra Residence',
      receipt_number: 'INV-SUP-20260508-0041',
      transaction_date: '2026-05-08',
      scan_date: '2026-05-08',
      total_amount: 185000,
      points_earned: 0,
      status: 'rejected',
      duplicate_reason: 'Struk ini sudah pernah di-scan sebelumnya (receipt_001). Poin tidak dapat dikreditkan dua kali.',
      image_url: 'https://images.unsplash.com/photo-1532372320978-9b4b0c74e24d?w=900&q=80',
      receipt_image_url: 'https://images.unsplash.com/photo-1532372320978-9b4b0c74e24d?w=900&q=80',
      ocr_raw_text: 'Duplicate receipt detected',
      created_date: '2026-05-08T15:30:00.000Z',
    },
  ],

  LotteryEntry: [
    {
      id: 'lentry_001',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      lottery_id: 'lottery_001',
      lottery_title: 'Resident Lucky Draw Bulanan',
      entry_count: 3,
      points_spent: 150,
      entry_numbers: ['LDR-001-0042', 'LDR-001-0043', 'LDR-001-0044'],
      spin_result: null,
      entry_date: '2026-05-03',
      created_date: '2026-05-03T10:00:00.000Z',
    },
    {
      id: 'lentry_002',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      lottery_id: 'lottery_002',
      lottery_title: 'Grand Prize Anniversary ION',
      entry_count: 2,
      points_spent: 200,
      entry_numbers: ['LDR-002-0018', 'LDR-002-0019'],
      spin_result: null,
      entry_date: '2026-05-05',
      created_date: '2026-05-05T11:00:00.000Z',
    },
    {
      id: 'lentry_003',
      user_email: 'resident@example.com',
      user_name: 'Budi Santoso',
      lottery_id: 'lottery_001',
      lottery_title: 'Resident Lucky Draw Bulanan',
      entry_count: 2,
      points_spent: 100,
      entry_numbers: ['LDR-001-0087', 'LDR-001-0088'],
      spin_result: null,
      entry_date: '2026-05-10',
      created_date: '2026-05-10T14:00:00.000Z',
    },
  ],
};

const entityNames = [
  'ActivityLog',
  'ApprovalWorkflow',
  'DepositInspectionClearance',
  'DepositRefundRequest',
  'Destination',
  'Event',
  'Inspection',
  'Lottery',
  'LotteryEntry',
  'Notification',
  'PermitApplication',
  'PermitDocument',
  'PermitRule',
  'Property',
  'RefundActivityLog',
  'RefundApprovalWorkflow',
  'RefundDocumentChecklist',
  'RefundLedger',
  'Reward',
  'RewardClaim',
  'ScannedReceipt',
  'Tenant',
  'Ticket',
  'Unit',
  'User',
  'UserPoints',
  'WorkItem',
];

let memoryData;

const clone = (value) => JSON.parse(JSON.stringify(value));

const getStorage = () => {
  if (typeof window === 'undefined') return null;
  return window.localStorage;
};

const normaliseData = (data) => {
  const next = { ...data };
  entityNames.forEach((name) => {
    if (!Array.isArray(next[name])) next[name] = [];
  });
  return next;
};

const readData = () => {
  const storage = getStorage();
  if (!storage) {
    memoryData = memoryData || clone(seedData);
    return normaliseData(memoryData);
  }

  const raw = storage.getItem(STORAGE_KEY);
  if (!raw) {
    const seeded = normaliseData(clone(seedData));
    storage.setItem(STORAGE_KEY, JSON.stringify(seeded));
    return seeded;
  }

  try {
    return normaliseData(JSON.parse(raw));
  } catch {
    const seeded = normaliseData(clone(seedData));
    storage.setItem(STORAGE_KEY, JSON.stringify(seeded));
    return seeded;
  }
};

const writeData = (data) => {
  const next = normaliseData(data);
  const storage = getStorage();
  if (!storage) {
    memoryData = clone(next);
    return next;
  }
  storage.setItem(STORAGE_KEY, JSON.stringify(next));
  return next;
};

const sortItems = (items, sort) => {
  if (!sort) return items;
  const descending = sort.startsWith('-');
  const field = descending ? sort.slice(1) : sort;
  return [...items].sort((a, b) => {
    const left = a?.[field] ?? '';
    const right = b?.[field] ?? '';
    if (left === right) return 0;
    return (left > right ? 1 : -1) * (descending ? -1 : 1);
  });
};

const applyLimit = (items, limit) => {
  if (!limit) return items;
  return items.slice(0, limit);
};

const matchesCriteria = (item, criteria = {}) =>
  Object.entries(criteria).every(([key, value]) => {
    if (value === undefined || value === null || value === '') return true;
    return item?.[key] === value;
  });

const createEntityClient = (entityName) => ({
  async list(sort, limit) {
    const data = readData();
    return clone(applyLimit(sortItems(data[entityName] || [], sort), limit));
  },
  async filter(criteria = {}, sort, limit) {
    const data = readData();
    const filtered = (data[entityName] || []).filter((item) => matchesCriteria(item, criteria));
    return clone(applyLimit(sortItems(filtered, sort), limit));
  },
  async create(payload) {
    const data = readData();
    const created = {
      id: payload?.id || `${entityName.toLowerCase()}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
      created_date: payload?.created_date || now(),
      ...payload,
    };
    data[entityName] = [created, ...(data[entityName] || [])];
    writeData(data);
    return clone(created);
  },
  async bulkCreate(payloads = []) {
    const created = [];
    for (const payload of payloads) {
      created.push(await this.create(payload));
    }
    return created;
  },
  async update(id, payload) {
    const data = readData();
    const items = data[entityName] || [];
    const index = items.findIndex((item) => item.id === id);
    if (index === -1) {
      throw new Error(`${entityName} with id ${id} was not found`);
    }
    const updated = {
      ...items[index],
      ...payload,
      updated_date: now(),
    };
    data[entityName] = items.map((item) => (item.id === id ? updated : item));
    writeData(data);
    return clone(updated);
  },
  async delete(id) {
    const data = readData();
    data[entityName] = (data[entityName] || []).filter((item) => item.id !== id);
    writeData(data);
    return { success: true };
  },
});

const getCurrentUser = () => {
  const storage = getStorage();
  if (!storage) return defaultUser;

  const raw = storage.getItem(USER_KEY);
  if (!raw) {
    storage.setItem(USER_KEY, JSON.stringify(defaultUser));
    storage.setItem('mock_role', defaultUser.role);
    return defaultUser;
  }

  try {
    return JSON.parse(raw);
  } catch {
    storage.setItem(USER_KEY, JSON.stringify(defaultUser));
    storage.setItem('mock_role', defaultUser.role);
    return defaultUser;
  }
};

const auth = {
  async me() {
    return clone(getCurrentUser());
  },
  logout(redirectUrl = '/Splash') {
    const storage = getStorage();
    storage?.removeItem(USER_KEY);
    storage?.removeItem('mock_role');
    if (typeof window !== 'undefined' && redirectUrl) {
      window.location.assign(redirectUrl);
    }
  },
  redirectToLogin(redirectUrl = '/Home') {
    if (typeof window === 'undefined') return;
    const params = new URLSearchParams({ redirect: redirectUrl });
    window.location.assign(`/MockLogin?${params.toString()}`);
  },
};

const integrations = {
  Core: {
    async UploadFile({ file }) {
      if (typeof URL !== 'undefined' && file) {
        return { file_url: URL.createObjectURL(file) };
      }
      return { file_url: '' };
    },
    async InvokeLLM(_options = {}) {
      return {
        merchant_name: 'Demo Merchant',
        transaction_date: new Date().toISOString().slice(0, 10),
        total_amount: 125000,
        confidence: 0.85,
        notes: 'Local demo OCR result',
      };
    },
  },
};

/** @type {Record<string, any>} */
const entities = entityNames.reduce((acc, name) => {
  acc[name] = createEntityClient(name);
  return acc;
}, {});

/** @type {any} */
export const appClient = {
  auth,
  entities,
  integrations,
};
